//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace InvenTacos.Entity.MSSQL
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SoftRestaurantEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SoftRestaurantEntities usando la cadena de conexión encontrada en la sección 'SoftRestaurantEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public SoftRestaurantEntities() : base("name=SoftRestaurantEntities", "SoftRestaurantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SoftRestaurantEntities.
        /// </summary>
        public SoftRestaurantEntities(string connectionString) : base(connectionString, "SoftRestaurantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SoftRestaurantEntities.
        /// </summary>
        public SoftRestaurantEntities(EntityConnection connection) : base(connection, "SoftRestaurantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<insumos> insumos
        {
            get
            {
                if ((_insumos == null))
                {
                    _insumos = base.CreateObjectSet<insumos>("insumos");
                }
                return _insumos;
            }
        }
        private ObjectSet<insumos> _insumos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<insumospresentaciones> insumospresentaciones
        {
            get
            {
                if ((_insumospresentaciones == null))
                {
                    _insumospresentaciones = base.CreateObjectSet<insumospresentaciones>("insumospresentaciones");
                }
                return _insumospresentaciones;
            }
        }
        private ObjectSet<insumospresentaciones> _insumospresentaciones;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<compras> compras
        {
            get
            {
                if ((_compras == null))
                {
                    _compras = base.CreateObjectSet<compras>("compras");
                }
                return _compras;
            }
        }
        private ObjectSet<compras> _compras;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet insumos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinsumos(insumos insumos)
        {
            base.AddObject("insumos", insumos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet insumospresentaciones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinsumospresentaciones(insumospresentaciones insumospresentaciones)
        {
            base.AddObject("insumospresentaciones", insumospresentaciones);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet compras. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocompras(compras compras)
        {
            base.AddObject("compras", compras);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftRestaurantModel", Name="compras")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class compras : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto compras.
        /// </summary>
        /// <param name="idcompra">Valor inicial de la propiedad idcompra.</param>
        public static compras Createcompras(global::System.Int64 idcompra)
        {
            compras compras = new compras();
            compras.idcompra = idcompra;
            return compras;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idcompra
        {
            get
            {
                return _idcompra;
            }
            set
            {
                if (_idcompra != value)
                {
                    OnidcompraChanging(value);
                    ReportPropertyChanging("idcompra");
                    _idcompra = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcompra");
                    OnidcompraChanged();
                }
            }
        }
        private global::System.Int64 _idcompra;
        partial void OnidcompraChanging(global::System.Int64 value);
        partial void OnidcompraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idempresa
        {
            get
            {
                return _idempresa;
            }
            set
            {
                OnidempresaChanging(value);
                ReportPropertyChanging("idempresa");
                _idempresa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idempresa");
                OnidempresaChanged();
            }
        }
        private global::System.String _idempresa;
        partial void OnidempresaChanging(global::System.String value);
        partial void OnidempresaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String folio
        {
            get
            {
                return _folio;
            }
            set
            {
                OnfolioChanging(value);
                ReportPropertyChanging("folio");
                _folio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("folio");
                OnfolioChanged();
            }
        }
        private global::System.String _folio;
        partial void OnfolioChanging(global::System.String value);
        partial void OnfolioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaaplicacion
        {
            get
            {
                return _fechaaplicacion;
            }
            set
            {
                OnfechaaplicacionChanging(value);
                ReportPropertyChanging("fechaaplicacion");
                _fechaaplicacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaaplicacion");
                OnfechaaplicacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaaplicacion;
        partial void OnfechaaplicacionChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaaplicacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idproveedor
        {
            get
            {
                return _idproveedor;
            }
            set
            {
                OnidproveedorChanging(value);
                ReportPropertyChanging("idproveedor");
                _idproveedor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idproveedor");
                OnidproveedorChanged();
            }
        }
        private global::System.String _idproveedor;
        partial void OnidproveedorChanging(global::System.String value);
        partial void OnidproveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String foliofactura
        {
            get
            {
                return _foliofactura;
            }
            set
            {
                OnfoliofacturaChanging(value);
                ReportPropertyChanging("foliofactura");
                _foliofactura = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("foliofactura");
                OnfoliofacturaChanged();
            }
        }
        private global::System.String _foliofactura;
        partial void OnfoliofacturaChanging(global::System.String value);
        partial void OnfoliofacturaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechafactura
        {
            get
            {
                return _fechafactura;
            }
            set
            {
                OnfechafacturaChanging(value);
                ReportPropertyChanging("fechafactura");
                _fechafactura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechafactura");
                OnfechafacturaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechafactura;
        partial void OnfechafacturaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechafacturaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> cancelado
        {
            get
            {
                return _cancelado;
            }
            set
            {
                OncanceladoChanging(value);
                ReportPropertyChanging("cancelado");
                _cancelado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cancelado");
                OncanceladoChanged();
            }
        }
        private Nullable<global::System.Boolean> _cancelado;
        partial void OncanceladoChanging(Nullable<global::System.Boolean> value);
        partial void OncanceladoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechavencimiento
        {
            get
            {
                return _fechavencimiento;
            }
            set
            {
                OnfechavencimientoChanging(value);
                ReportPropertyChanging("fechavencimiento");
                _fechavencimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechavencimiento");
                OnfechavencimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechavencimiento;
        partial void OnfechavencimientoChanging(Nullable<global::System.DateTime> value);
        partial void OnfechavencimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuariocancelo
        {
            get
            {
                return _usuariocancelo;
            }
            set
            {
                OnusuariocanceloChanging(value);
                ReportPropertyChanging("usuariocancelo");
                _usuariocancelo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuariocancelo");
                OnusuariocanceloChanged();
            }
        }
        private global::System.String _usuariocancelo;
        partial void OnusuariocanceloChanging(global::System.String value);
        partial void OnusuariocanceloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String referencia
        {
            get
            {
                return _referencia;
            }
            set
            {
                OnreferenciaChanging(value);
                ReportPropertyChanging("referencia");
                _referencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("referencia");
                OnreferenciaChanged();
            }
        }
        private global::System.String _referencia;
        partial void OnreferenciaChanging(global::System.String value);
        partial void OnreferenciaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> descuento
        {
            get
            {
                return _descuento;
            }
            set
            {
                OndescuentoChanging(value);
                ReportPropertyChanging("descuento");
                _descuento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("descuento");
                OndescuentoChanged();
            }
        }
        private Nullable<global::System.Decimal> _descuento;
        partial void OndescuentoChanging(Nullable<global::System.Decimal> value);
        partial void OndescuentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> subtotal
        {
            get
            {
                return _subtotal;
            }
            set
            {
                OnsubtotalChanging(value);
                ReportPropertyChanging("subtotal");
                _subtotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("subtotal");
                OnsubtotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _subtotal;
        partial void OnsubtotalChanging(Nullable<global::System.Decimal> value);
        partial void OnsubtotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> impuesto1
        {
            get
            {
                return _impuesto1;
            }
            set
            {
                Onimpuesto1Changing(value);
                ReportPropertyChanging("impuesto1");
                _impuesto1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impuesto1");
                Onimpuesto1Changed();
            }
        }
        private Nullable<global::System.Decimal> _impuesto1;
        partial void Onimpuesto1Changing(Nullable<global::System.Decimal> value);
        partial void Onimpuesto1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> impuesto2
        {
            get
            {
                return _impuesto2;
            }
            set
            {
                Onimpuesto2Changing(value);
                ReportPropertyChanging("impuesto2");
                _impuesto2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impuesto2");
                Onimpuesto2Changed();
            }
        }
        private Nullable<global::System.Decimal> _impuesto2;
        partial void Onimpuesto2Changing(Nullable<global::System.Decimal> value);
        partial void Onimpuesto2Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> impuesto3
        {
            get
            {
                return _impuesto3;
            }
            set
            {
                Onimpuesto3Changing(value);
                ReportPropertyChanging("impuesto3");
                _impuesto3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impuesto3");
                Onimpuesto3Changed();
            }
        }
        private Nullable<global::System.Decimal> _impuesto3;
        partial void Onimpuesto3Changing(Nullable<global::System.Decimal> value);
        partial void Onimpuesto3Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private Nullable<global::System.Decimal> _total;
        partial void OntotalChanging(Nullable<global::System.Decimal> value);
        partial void OntotalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> fiscal
        {
            get
            {
                return _fiscal;
            }
            set
            {
                OnfiscalChanging(value);
                ReportPropertyChanging("fiscal");
                _fiscal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fiscal");
                OnfiscalChanged();
            }
        }
        private Nullable<global::System.Boolean> _fiscal;
        partial void OnfiscalChanging(Nullable<global::System.Boolean> value);
        partial void OnfiscalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftRestaurantModel", Name="insumos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class insumos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto insumos.
        /// </summary>
        /// <param name="id_insumo">Valor inicial de la propiedad id_insumo.</param>
        public static insumos Createinsumos(global::System.String id_insumo)
        {
            insumos insumos = new insumos();
            insumos.id_insumo = id_insumo;
            return insumos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_insumo
        {
            get
            {
                return _id_insumo;
            }
            set
            {
                if (_id_insumo != value)
                {
                    Onid_insumoChanging(value);
                    ReportPropertyChanging("id_insumo");
                    _id_insumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_insumo");
                    Onid_insumoChanged();
                }
            }
        }
        private global::System.String _id_insumo;
        partial void Onid_insumoChanging(global::System.String value);
        partial void Onid_insumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idgruposi
        {
            get
            {
                return _idgruposi;
            }
            set
            {
                OnidgruposiChanging(value);
                ReportPropertyChanging("idgruposi");
                _idgruposi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idgruposi");
                OnidgruposiChanged();
            }
        }
        private global::System.String _idgruposi;
        partial void OnidgruposiChanging(global::System.String value);
        partial void OnidgruposiChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> elaborado
        {
            get
            {
                return _elaborado;
            }
            set
            {
                OnelaboradoChanging(value);
                ReportPropertyChanging("elaborado");
                _elaborado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("elaborado");
                OnelaboradoChanged();
            }
        }
        private Nullable<global::System.Boolean> _elaborado;
        partial void OnelaboradoChanging(Nullable<global::System.Boolean> value);
        partial void OnelaboradoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> rendimientoelaborado
        {
            get
            {
                return _rendimientoelaborado;
            }
            set
            {
                OnrendimientoelaboradoChanging(value);
                ReportPropertyChanging("rendimientoelaborado");
                _rendimientoelaborado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rendimientoelaborado");
                OnrendimientoelaboradoChanged();
            }
        }
        private Nullable<global::System.Decimal> _rendimientoelaborado;
        partial void OnrendimientoelaboradoChanging(Nullable<global::System.Decimal> value);
        partial void OnrendimientoelaboradoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftRestaurantModel", Name="insumospresentaciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class insumospresentaciones : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto insumospresentaciones.
        /// </summary>
        /// <param name="id_insumospresentaciones">Valor inicial de la propiedad id_insumospresentaciones.</param>
        public static insumospresentaciones Createinsumospresentaciones(global::System.String id_insumospresentaciones)
        {
            insumospresentaciones insumospresentaciones = new insumospresentaciones();
            insumospresentaciones.id_insumospresentaciones = id_insumospresentaciones;
            return insumospresentaciones;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_insumospresentaciones
        {
            get
            {
                return _id_insumospresentaciones;
            }
            set
            {
                if (_id_insumospresentaciones != value)
                {
                    Onid_insumospresentacionesChanging(value);
                    ReportPropertyChanging("id_insumospresentaciones");
                    _id_insumospresentaciones = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_insumospresentaciones");
                    Onid_insumospresentacionesChanged();
                }
            }
        }
        private global::System.String _id_insumospresentaciones;
        partial void Onid_insumospresentacionesChanging(global::System.String value);
        partial void Onid_insumospresentacionesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String id_insumo
        {
            get
            {
                return _id_insumo;
            }
            set
            {
                Onid_insumoChanging(value);
                ReportPropertyChanging("id_insumo");
                _id_insumo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("id_insumo");
                Onid_insumoChanged();
            }
        }
        private global::System.String _id_insumo;
        partial void Onid_insumoChanging(global::System.String value);
        partial void Onid_insumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idgruposi
        {
            get
            {
                return _idgruposi;
            }
            set
            {
                OnidgruposiChanging(value);
                ReportPropertyChanging("idgruposi");
                _idgruposi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idgruposi");
                OnidgruposiChanged();
            }
        }
        private global::System.String _idgruposi;
        partial void OnidgruposiChanging(global::System.String value);
        partial void OnidgruposiChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> rendimiento
        {
            get
            {
                return _rendimiento;
            }
            set
            {
                OnrendimientoChanging(value);
                ReportPropertyChanging("rendimiento");
                _rendimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rendimiento");
                OnrendimientoChanged();
            }
        }
        private Nullable<global::System.Decimal> _rendimiento;
        partial void OnrendimientoChanging(Nullable<global::System.Decimal> value);
        partial void OnrendimientoChanged();

        #endregion

    
    }

    #endregion

    
}
