//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace InvenTacos.Entity.MSSQL
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SoftRestaurantEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SoftRestaurantEntities usando la cadena de conexión encontrada en la sección 'SoftRestaurantEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public SoftRestaurantEntities() : base("name=SoftRestaurantEntities", "SoftRestaurantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SoftRestaurantEntities.
        /// </summary>
        public SoftRestaurantEntities(string connectionString) : base(connectionString, "SoftRestaurantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SoftRestaurantEntities.
        /// </summary>
        public SoftRestaurantEntities(EntityConnection connection) : base(connection, "SoftRestaurantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<insumos> insumos
        {
            get
            {
                if ((_insumos == null))
                {
                    _insumos = base.CreateObjectSet<insumos>("insumos");
                }
                return _insumos;
            }
        }
        private ObjectSet<insumos> _insumos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<insumospresentaciones> insumospresentaciones
        {
            get
            {
                if ((_insumospresentaciones == null))
                {
                    _insumospresentaciones = base.CreateObjectSet<insumospresentaciones>("insumospresentaciones");
                }
                return _insumospresentaciones;
            }
        }
        private ObjectSet<insumospresentaciones> _insumospresentaciones;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet insumos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinsumos(insumos insumos)
        {
            base.AddObject("insumos", insumos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet insumospresentaciones. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinsumospresentaciones(insumospresentaciones insumospresentaciones)
        {
            base.AddObject("insumospresentaciones", insumospresentaciones);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftRestaurantModel", Name="insumos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class insumos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto insumos.
        /// </summary>
        /// <param name="idinsumo">Valor inicial de la propiedad idinsumo.</param>
        public static insumos Createinsumos(global::System.String idinsumo)
        {
            insumos insumos = new insumos();
            insumos.idinsumo = idinsumo;
            return insumos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idinsumo
        {
            get
            {
                return _idinsumo;
            }
            set
            {
                if (_idinsumo != value)
                {
                    OnidinsumoChanging(value);
                    ReportPropertyChanging("idinsumo");
                    _idinsumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idinsumo");
                    OnidinsumoChanged();
                }
            }
        }
        private global::System.String _idinsumo;
        partial void OnidinsumoChanging(global::System.String value);
        partial void OnidinsumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idgruposi
        {
            get
            {
                return _idgruposi;
            }
            set
            {
                OnidgruposiChanging(value);
                ReportPropertyChanging("idgruposi");
                _idgruposi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idgruposi");
                OnidgruposiChanged();
            }
        }
        private global::System.String _idgruposi;
        partial void OnidgruposiChanging(global::System.String value);
        partial void OnidgruposiChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> elaborado
        {
            get
            {
                return _elaborado;
            }
            set
            {
                OnelaboradoChanging(value);
                ReportPropertyChanging("elaborado");
                _elaborado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("elaborado");
                OnelaboradoChanged();
            }
        }
        private Nullable<global::System.Boolean> _elaborado;
        partial void OnelaboradoChanging(Nullable<global::System.Boolean> value);
        partial void OnelaboradoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> rendimientoelaborado
        {
            get
            {
                return _rendimientoelaborado;
            }
            set
            {
                OnrendimientoelaboradoChanging(value);
                ReportPropertyChanging("rendimientoelaborado");
                _rendimientoelaborado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rendimientoelaborado");
                OnrendimientoelaboradoChanged();
            }
        }
        private Nullable<global::System.Decimal> _rendimientoelaborado;
        partial void OnrendimientoelaboradoChanging(Nullable<global::System.Decimal> value);
        partial void OnrendimientoelaboradoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoftRestaurantModel", Name="insumospresentaciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class insumospresentaciones : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto insumospresentaciones.
        /// </summary>
        /// <param name="idinsumospresentaciones">Valor inicial de la propiedad idinsumospresentaciones.</param>
        public static insumospresentaciones Createinsumospresentaciones(global::System.String idinsumospresentaciones)
        {
            insumospresentaciones insumospresentaciones = new insumospresentaciones();
            insumospresentaciones.idinsumospresentaciones = idinsumospresentaciones;
            return insumospresentaciones;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idinsumospresentaciones
        {
            get
            {
                return _idinsumospresentaciones;
            }
            set
            {
                if (_idinsumospresentaciones != value)
                {
                    OnidinsumospresentacionesChanging(value);
                    ReportPropertyChanging("idinsumospresentaciones");
                    _idinsumospresentaciones = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idinsumospresentaciones");
                    OnidinsumospresentacionesChanged();
                }
            }
        }
        private global::System.String _idinsumospresentaciones;
        partial void OnidinsumospresentacionesChanging(global::System.String value);
        partial void OnidinsumospresentacionesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idinsumo
        {
            get
            {
                return _idinsumo;
            }
            set
            {
                OnidinsumoChanging(value);
                ReportPropertyChanging("idinsumo");
                _idinsumo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idinsumo");
                OnidinsumoChanged();
            }
        }
        private global::System.String _idinsumo;
        partial void OnidinsumoChanging(global::System.String value);
        partial void OnidinsumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String idgruposi
        {
            get
            {
                return _idgruposi;
            }
            set
            {
                OnidgruposiChanging(value);
                ReportPropertyChanging("idgruposi");
                _idgruposi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("idgruposi");
                OnidgruposiChanged();
            }
        }
        private global::System.String _idgruposi;
        partial void OnidgruposiChanging(global::System.String value);
        partial void OnidgruposiChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> rendimiento
        {
            get
            {
                return _rendimiento;
            }
            set
            {
                OnrendimientoChanging(value);
                ReportPropertyChanging("rendimiento");
                _rendimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rendimiento");
                OnrendimientoChanged();
            }
        }
        private Nullable<global::System.Decimal> _rendimiento;
        partial void OnrendimientoChanging(Nullable<global::System.Decimal> value);
        partial void OnrendimientoChanged();

        #endregion

    
    }

    #endregion

    
}
