//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace InvenTacos.Entity.MySQL
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class TacosInventarioEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto TacosInventarioEntities usando la cadena de conexión encontrada en la sección 'TacosInventarioEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public TacosInventarioEntities() : base("name=TacosInventarioEntities", "TacosInventarioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TacosInventarioEntities.
        /// </summary>
        public TacosInventarioEntities(string connectionString) : base(connectionString, "TacosInventarioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TacosInventarioEntities.
        /// </summary>
        public TacosInventarioEntities(EntityConnection connection) : base(connection, "TacosInventarioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<inventario_diarios> inventario_diarios
        {
            get
            {
                if ((_inventario_diarios == null))
                {
                    _inventario_diarios = base.CreateObjectSet<inventario_diarios>("inventario_diarios");
                }
                return _inventario_diarios;
            }
        }
        private ObjectSet<inventario_diarios> _inventario_diarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<inventario_insumos> inventario_insumos
        {
            get
            {
                if ((_inventario_insumos == null))
                {
                    _inventario_insumos = base.CreateObjectSet<inventario_insumos>("inventario_insumos");
                }
                return _inventario_insumos;
            }
        }
        private ObjectSet<inventario_insumos> _inventario_insumos;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet inventario_diarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinventario_diarios(inventario_diarios inventario_diarios)
        {
            base.AddObject("inventario_diarios", inventario_diarios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet inventario_insumos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinventario_insumos(inventario_insumos inventario_insumos)
        {
            base.AddObject("inventario_insumos", inventario_insumos);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="inventario_diarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class inventario_diarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto inventario_diarios.
        /// </summary>
        /// <param name="idinsumo">Valor inicial de la propiedad idinsumo.</param>
        /// <param name="cantidad_crudo">Valor inicial de la propiedad cantidad_crudo.</param>
        /// <param name="cantidad_cocido">Valor inicial de la propiedad cantidad_cocido.</param>
        /// <param name="cantidad_total">Valor inicial de la propiedad cantidad_total.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        public static inventario_diarios Createinventario_diarios(global::System.String idinsumo, global::System.Decimal cantidad_crudo, global::System.Decimal cantidad_cocido, global::System.Decimal cantidad_total, global::System.DateTime fecha)
        {
            inventario_diarios inventario_diarios = new inventario_diarios();
            inventario_diarios.idinsumo = idinsumo;
            inventario_diarios.cantidad_crudo = cantidad_crudo;
            inventario_diarios.cantidad_cocido = cantidad_cocido;
            inventario_diarios.cantidad_total = cantidad_total;
            inventario_diarios.fecha = fecha;
            return inventario_diarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idinsumo
        {
            get
            {
                return _idinsumo;
            }
            set
            {
                if (_idinsumo != value)
                {
                    OnidinsumoChanging(value);
                    ReportPropertyChanging("idinsumo");
                    _idinsumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idinsumo");
                    OnidinsumoChanged();
                }
            }
        }
        private global::System.String _idinsumo;
        partial void OnidinsumoChanging(global::System.String value);
        partial void OnidinsumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad_crudo
        {
            get
            {
                return _cantidad_crudo;
            }
            set
            {
                Oncantidad_crudoChanging(value);
                ReportPropertyChanging("cantidad_crudo");
                _cantidad_crudo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad_crudo");
                Oncantidad_crudoChanged();
            }
        }
        private global::System.Decimal _cantidad_crudo;
        partial void Oncantidad_crudoChanging(global::System.Decimal value);
        partial void Oncantidad_crudoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad_cocido
        {
            get
            {
                return _cantidad_cocido;
            }
            set
            {
                Oncantidad_cocidoChanging(value);
                ReportPropertyChanging("cantidad_cocido");
                _cantidad_cocido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad_cocido");
                Oncantidad_cocidoChanged();
            }
        }
        private global::System.Decimal _cantidad_cocido;
        partial void Oncantidad_cocidoChanging(global::System.Decimal value);
        partial void Oncantidad_cocidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad_total
        {
            get
            {
                return _cantidad_total;
            }
            set
            {
                Oncantidad_totalChanging(value);
                ReportPropertyChanging("cantidad_total");
                _cantidad_total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad_total");
                Oncantidad_totalChanged();
            }
        }
        private global::System.Decimal _cantidad_total;
        partial void Oncantidad_totalChanging(global::System.Decimal value);
        partial void Oncantidad_totalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                if (_fecha != value)
                {
                    OnfechaChanging(value);
                    ReportPropertyChanging("fecha");
                    _fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha");
                    OnfechaChanged();
                }
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="inventario_insumos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class inventario_insumos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto inventario_insumos.
        /// </summary>
        /// <param name="idinsumo">Valor inicial de la propiedad idinsumo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        public static inventario_insumos Createinventario_insumos(global::System.String idinsumo, global::System.String descripcion, global::System.String unidad)
        {
            inventario_insumos inventario_insumos = new inventario_insumos();
            inventario_insumos.idinsumo = idinsumo;
            inventario_insumos.descripcion = descripcion;
            inventario_insumos.unidad = unidad;
            return inventario_insumos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idinsumo
        {
            get
            {
                return _idinsumo;
            }
            set
            {
                if (_idinsumo != value)
                {
                    OnidinsumoChanging(value);
                    ReportPropertyChanging("idinsumo");
                    _idinsumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idinsumo");
                    OnidinsumoChanged();
                }
            }
        }
        private global::System.String _idinsumo;
        partial void OnidinsumoChanging(global::System.String value);
        partial void OnidinsumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> rendimiento
        {
            get
            {
                return _rendimiento;
            }
            set
            {
                OnrendimientoChanging(value);
                ReportPropertyChanging("rendimiento");
                _rendimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rendimiento");
                OnrendimientoChanged();
            }
        }
        private Nullable<global::System.Decimal> _rendimiento;
        partial void OnrendimientoChanging(Nullable<global::System.Decimal> value);
        partial void OnrendimientoChanged();

        #endregion

    
    }

    #endregion

    
}
