//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("TacosInventariosModel", "fk_conceptos", "conceptos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvenTacos.Entity.MySQL.conceptos), "prestamos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvenTacos.Entity.MySQL.prestamos), true)]
[assembly: EdmRelationshipAttribute("TacosInventariosModel", "FK_insum", "insumos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvenTacos.Entity.MySQL.insumos), "recetas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvenTacos.Entity.MySQL.recetas), true)]
[assembly: EdmRelationshipAttribute("TacosInventariosModel", "fk_insumos", "insumos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvenTacos.Entity.MySQL.insumos), "prestamos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvenTacos.Entity.MySQL.prestamos), true)]
[assembly: EdmRelationshipAttribute("TacosInventariosModel", "FK_prod", "productos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvenTacos.Entity.MySQL.productos), "recetas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvenTacos.Entity.MySQL.recetas), true)]
[assembly: EdmRelationshipAttribute("TacosInventariosModel", "FK_productos", "productos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(InvenTacos.Entity.MySQL.productos), "ventas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(InvenTacos.Entity.MySQL.ventas), true)]

#endregion

namespace InvenTacos.Entity.MySQL
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class TacosInventarioEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto TacosInventarioEntities usando la cadena de conexión encontrada en la sección 'TacosInventarioEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public TacosInventarioEntities() : base("name=TacosInventarioEntities", "TacosInventarioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TacosInventarioEntities.
        /// </summary>
        public TacosInventarioEntities(string connectionString) : base(connectionString, "TacosInventarioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TacosInventarioEntities.
        /// </summary>
        public TacosInventarioEntities(EntityConnection connection) : base(connection, "TacosInventarioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<compras> compras
        {
            get
            {
                if ((_compras == null))
                {
                    _compras = base.CreateObjectSet<compras>("compras");
                }
                return _compras;
            }
        }
        private ObjectSet<compras> _compras;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<conceptos> conceptos
        {
            get
            {
                if ((_conceptos == null))
                {
                    _conceptos = base.CreateObjectSet<conceptos>("conceptos");
                }
                return _conceptos;
            }
        }
        private ObjectSet<conceptos> _conceptos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<insumos> insumos
        {
            get
            {
                if ((_insumos == null))
                {
                    _insumos = base.CreateObjectSet<insumos>("insumos");
                }
                return _insumos;
            }
        }
        private ObjectSet<insumos> _insumos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<insumos_seleccionados> insumos_seleccionados
        {
            get
            {
                if ((_insumos_seleccionados == null))
                {
                    _insumos_seleccionados = base.CreateObjectSet<insumos_seleccionados>("insumos_seleccionados");
                }
                return _insumos_seleccionados;
            }
        }
        private ObjectSet<insumos_seleccionados> _insumos_seleccionados;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<inventarios_diarios> inventarios_diarios
        {
            get
            {
                if ((_inventarios_diarios == null))
                {
                    _inventarios_diarios = base.CreateObjectSet<inventarios_diarios>("inventarios_diarios");
                }
                return _inventarios_diarios;
            }
        }
        private ObjectSet<inventarios_diarios> _inventarios_diarios;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<prestamos> prestamos
        {
            get
            {
                if ((_prestamos == null))
                {
                    _prestamos = base.CreateObjectSet<prestamos>("prestamos");
                }
                return _prestamos;
            }
        }
        private ObjectSet<prestamos> _prestamos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<productos> productos
        {
            get
            {
                if ((_productos == null))
                {
                    _productos = base.CreateObjectSet<productos>("productos");
                }
                return _productos;
            }
        }
        private ObjectSet<productos> _productos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<recetas> recetas
        {
            get
            {
                if ((_recetas == null))
                {
                    _recetas = base.CreateObjectSet<recetas>("recetas");
                }
                return _recetas;
            }
        }
        private ObjectSet<recetas> _recetas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ventas> ventas
        {
            get
            {
                if ((_ventas == null))
                {
                    _ventas = base.CreateObjectSet<ventas>("ventas");
                }
                return _ventas;
            }
        }
        private ObjectSet<ventas> _ventas;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet compras. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocompras(compras compras)
        {
            base.AddObject("compras", compras);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet conceptos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToconceptos(conceptos conceptos)
        {
            base.AddObject("conceptos", conceptos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet insumos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinsumos(insumos insumos)
        {
            base.AddObject("insumos", insumos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet insumos_seleccionados. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinsumos_seleccionados(insumos_seleccionados insumos_seleccionados)
        {
            base.AddObject("insumos_seleccionados", insumos_seleccionados);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet inventarios_diarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToinventarios_diarios(inventarios_diarios inventarios_diarios)
        {
            base.AddObject("inventarios_diarios", inventarios_diarios);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet prestamos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToprestamos(prestamos prestamos)
        {
            base.AddObject("prestamos", prestamos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet productos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToproductos(productos productos)
        {
            base.AddObject("productos", productos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet recetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTorecetas(recetas recetas)
        {
            base.AddObject("recetas", recetas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ventas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToventas(ventas ventas)
        {
            base.AddObject("ventas", ventas);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="compras")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class compras : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto compras.
        /// </summary>
        /// <param name="id_compra">Valor inicial de la propiedad id_compra.</param>
        /// <param name="id_insumo">Valor inicial de la propiedad id_insumo.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        public static compras Createcompras(global::System.Int64 id_compra, global::System.String id_insumo, global::System.Decimal cantidad, global::System.DateTime fecha)
        {
            compras compras = new compras();
            compras.id_compra = id_compra;
            compras.id_insumo = id_insumo;
            compras.cantidad = cantidad;
            compras.fecha = fecha;
            return compras;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_compra
        {
            get
            {
                return _id_compra;
            }
            set
            {
                if (_id_compra != value)
                {
                    Onid_compraChanging(value);
                    ReportPropertyChanging("id_compra");
                    _id_compra = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_compra");
                    Onid_compraChanged();
                }
            }
        }
        private global::System.Int64 _id_compra;
        partial void Onid_compraChanging(global::System.Int64 value);
        partial void Onid_compraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_insumo
        {
            get
            {
                return _id_insumo;
            }
            set
            {
                if (_id_insumo != value)
                {
                    Onid_insumoChanging(value);
                    ReportPropertyChanging("id_insumo");
                    _id_insumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_insumo");
                    Onid_insumoChanged();
                }
            }
        }
        private global::System.String _id_insumo;
        partial void Onid_insumoChanging(global::System.String value);
        partial void Onid_insumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                if (_fecha != value)
                {
                    OnfechaChanging(value);
                    ReportPropertyChanging("fecha");
                    _fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha");
                    OnfechaChanged();
                }
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="conceptos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class conceptos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto conceptos.
        /// </summary>
        /// <param name="idconcepto">Valor inicial de la propiedad idconcepto.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="tipo">Valor inicial de la propiedad tipo.</param>
        /// <param name="descripciontipo">Valor inicial de la propiedad descripciontipo.</param>
        public static conceptos Createconceptos(global::System.String idconcepto, global::System.String descripcion, global::System.Byte tipo, global::System.String descripciontipo)
        {
            conceptos conceptos = new conceptos();
            conceptos.idconcepto = idconcepto;
            conceptos.descripcion = descripcion;
            conceptos.tipo = tipo;
            conceptos.descripciontipo = descripciontipo;
            return conceptos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idconcepto
        {
            get
            {
                return _idconcepto;
            }
            set
            {
                if (_idconcepto != value)
                {
                    OnidconceptoChanging(value);
                    ReportPropertyChanging("idconcepto");
                    _idconcepto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idconcepto");
                    OnidconceptoChanged();
                }
            }
        }
        private global::System.String _idconcepto;
        partial void OnidconceptoChanging(global::System.String value);
        partial void OnidconceptoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.Byte _tipo;
        partial void OntipoChanging(global::System.Byte value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripciontipo
        {
            get
            {
                return _descripciontipo;
            }
            set
            {
                OndescripciontipoChanging(value);
                ReportPropertyChanging("descripciontipo");
                _descripciontipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripciontipo");
                OndescripciontipoChanged();
            }
        }
        private global::System.String _descripciontipo;
        partial void OndescripciontipoChanging(global::System.String value);
        partial void OndescripciontipoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "fk_conceptos", "prestamos")]
        public EntityCollection<prestamos> prestamos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<prestamos>("TacosInventariosModel.fk_conceptos", "prestamos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<prestamos>("TacosInventariosModel.fk_conceptos", "prestamos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="insumos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class insumos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto insumos.
        /// </summary>
        /// <param name="id_insumo">Valor inicial de la propiedad id_insumo.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        public static insumos Createinsumos(global::System.String id_insumo, global::System.String descripcion, global::System.String unidad)
        {
            insumos insumos = new insumos();
            insumos.id_insumo = id_insumo;
            insumos.descripcion = descripcion;
            insumos.unidad = unidad;
            return insumos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_insumo
        {
            get
            {
                return _id_insumo;
            }
            set
            {
                if (_id_insumo != value)
                {
                    Onid_insumoChanging(value);
                    ReportPropertyChanging("id_insumo");
                    _id_insumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_insumo");
                    Onid_insumoChanged();
                }
            }
        }
        private global::System.String _id_insumo;
        partial void Onid_insumoChanging(global::System.String value);
        partial void Onid_insumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> rendimiento
        {
            get
            {
                return _rendimiento;
            }
            set
            {
                OnrendimientoChanging(value);
                ReportPropertyChanging("rendimiento");
                _rendimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rendimiento");
                OnrendimientoChanged();
            }
        }
        private Nullable<global::System.Decimal> _rendimiento;
        partial void OnrendimientoChanging(Nullable<global::System.Decimal> value);
        partial void OnrendimientoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "FK_insum", "recetas")]
        public EntityCollection<recetas> recetas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recetas>("TacosInventariosModel.FK_insum", "recetas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recetas>("TacosInventariosModel.FK_insum", "recetas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "fk_insumos", "prestamos")]
        public EntityCollection<prestamos> prestamos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<prestamos>("TacosInventariosModel.fk_insumos", "prestamos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<prestamos>("TacosInventariosModel.fk_insumos", "prestamos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="insumos_seleccionados")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class insumos_seleccionados : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto insumos_seleccionados.
        /// </summary>
        /// <param name="id_insumo">Valor inicial de la propiedad id_insumo.</param>
        public static insumos_seleccionados Createinsumos_seleccionados(global::System.String id_insumo)
        {
            insumos_seleccionados insumos_seleccionados = new insumos_seleccionados();
            insumos_seleccionados.id_insumo = id_insumo;
            return insumos_seleccionados;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_insumo
        {
            get
            {
                return _id_insumo;
            }
            set
            {
                if (_id_insumo != value)
                {
                    Onid_insumoChanging(value);
                    ReportPropertyChanging("id_insumo");
                    _id_insumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_insumo");
                    Onid_insumoChanged();
                }
            }
        }
        private global::System.String _id_insumo;
        partial void Onid_insumoChanging(global::System.String value);
        partial void Onid_insumoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="inventarios_diarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class inventarios_diarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto inventarios_diarios.
        /// </summary>
        /// <param name="id_insumo">Valor inicial de la propiedad id_insumo.</param>
        /// <param name="cantidad_crudo">Valor inicial de la propiedad cantidad_crudo.</param>
        /// <param name="cantidad_cocido">Valor inicial de la propiedad cantidad_cocido.</param>
        /// <param name="cantidad_total">Valor inicial de la propiedad cantidad_total.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        public static inventarios_diarios Createinventarios_diarios(global::System.String id_insumo, global::System.Decimal cantidad_crudo, global::System.Decimal cantidad_cocido, global::System.Decimal cantidad_total, global::System.DateTime fecha)
        {
            inventarios_diarios inventarios_diarios = new inventarios_diarios();
            inventarios_diarios.id_insumo = id_insumo;
            inventarios_diarios.cantidad_crudo = cantidad_crudo;
            inventarios_diarios.cantidad_cocido = cantidad_cocido;
            inventarios_diarios.cantidad_total = cantidad_total;
            inventarios_diarios.fecha = fecha;
            return inventarios_diarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_insumo
        {
            get
            {
                return _id_insumo;
            }
            set
            {
                if (_id_insumo != value)
                {
                    Onid_insumoChanging(value);
                    ReportPropertyChanging("id_insumo");
                    _id_insumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_insumo");
                    Onid_insumoChanged();
                }
            }
        }
        private global::System.String _id_insumo;
        partial void Onid_insumoChanging(global::System.String value);
        partial void Onid_insumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad_crudo
        {
            get
            {
                return _cantidad_crudo;
            }
            set
            {
                Oncantidad_crudoChanging(value);
                ReportPropertyChanging("cantidad_crudo");
                _cantidad_crudo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad_crudo");
                Oncantidad_crudoChanged();
            }
        }
        private global::System.Decimal _cantidad_crudo;
        partial void Oncantidad_crudoChanging(global::System.Decimal value);
        partial void Oncantidad_crudoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad_cocido
        {
            get
            {
                return _cantidad_cocido;
            }
            set
            {
                Oncantidad_cocidoChanging(value);
                ReportPropertyChanging("cantidad_cocido");
                _cantidad_cocido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad_cocido");
                Oncantidad_cocidoChanged();
            }
        }
        private global::System.Decimal _cantidad_cocido;
        partial void Oncantidad_cocidoChanging(global::System.Decimal value);
        partial void Oncantidad_cocidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad_total
        {
            get
            {
                return _cantidad_total;
            }
            set
            {
                Oncantidad_totalChanging(value);
                ReportPropertyChanging("cantidad_total");
                _cantidad_total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad_total");
                Oncantidad_totalChanged();
            }
        }
        private global::System.Decimal _cantidad_total;
        partial void Oncantidad_totalChanging(global::System.Decimal value);
        partial void Oncantidad_totalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                if (_fecha != value)
                {
                    OnfechaChanging(value);
                    ReportPropertyChanging("fecha");
                    _fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha");
                    OnfechaChanged();
                }
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="prestamos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class prestamos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto prestamos.
        /// </summary>
        /// <param name="idinsumo">Valor inicial de la propiedad idinsumo.</param>
        /// <param name="idconcepto">Valor inicial de la propiedad idconcepto.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        public static prestamos Createprestamos(global::System.String idinsumo, global::System.String idconcepto, global::System.Decimal cantidad, global::System.DateTime fecha)
        {
            prestamos prestamos = new prestamos();
            prestamos.idinsumo = idinsumo;
            prestamos.idconcepto = idconcepto;
            prestamos.cantidad = cantidad;
            prestamos.fecha = fecha;
            return prestamos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idinsumo
        {
            get
            {
                return _idinsumo;
            }
            set
            {
                if (_idinsumo != value)
                {
                    OnidinsumoChanging(value);
                    ReportPropertyChanging("idinsumo");
                    _idinsumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idinsumo");
                    OnidinsumoChanged();
                }
            }
        }
        private global::System.String _idinsumo;
        partial void OnidinsumoChanging(global::System.String value);
        partial void OnidinsumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idconcepto
        {
            get
            {
                return _idconcepto;
            }
            set
            {
                if (_idconcepto != value)
                {
                    OnidconceptoChanging(value);
                    ReportPropertyChanging("idconcepto");
                    _idconcepto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idconcepto");
                    OnidconceptoChanged();
                }
            }
        }
        private global::System.String _idconcepto;
        partial void OnidconceptoChanging(global::System.String value);
        partial void OnidconceptoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                if (_fecha != value)
                {
                    OnfechaChanging(value);
                    ReportPropertyChanging("fecha");
                    _fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha");
                    OnfechaChanged();
                }
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "fk_conceptos", "conceptos")]
        public conceptos conceptos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<conceptos>("TacosInventariosModel.fk_conceptos", "conceptos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<conceptos>("TacosInventariosModel.fk_conceptos", "conceptos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<conceptos> conceptosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<conceptos>("TacosInventariosModel.fk_conceptos", "conceptos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<conceptos>("TacosInventariosModel.fk_conceptos", "conceptos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "fk_insumos", "insumos")]
        public insumos insumos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<insumos>("TacosInventariosModel.fk_insumos", "insumos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<insumos>("TacosInventariosModel.fk_insumos", "insumos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<insumos> insumosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<insumos>("TacosInventariosModel.fk_insumos", "insumos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<insumos>("TacosInventariosModel.fk_insumos", "insumos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="productos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class productos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto productos.
        /// </summary>
        /// <param name="id_producto">Valor inicial de la propiedad id_producto.</param>
        /// <param name="producto">Valor inicial de la propiedad producto.</param>
        public static productos Createproductos(global::System.String id_producto, global::System.String producto)
        {
            productos productos = new productos();
            productos.id_producto = id_producto;
            productos.producto = producto;
            return productos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                if (_id_producto != value)
                {
                    Onid_productoChanging(value);
                    ReportPropertyChanging("id_producto");
                    _id_producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_producto");
                    Onid_productoChanged();
                }
            }
        }
        private global::System.String _id_producto;
        partial void Onid_productoChanging(global::System.String value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String producto
        {
            get
            {
                return _producto;
            }
            set
            {
                OnproductoChanging(value);
                ReportPropertyChanging("producto");
                _producto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("producto");
                OnproductoChanged();
            }
        }
        private global::System.String _producto;
        partial void OnproductoChanging(global::System.String value);
        partial void OnproductoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "FK_prod", "recetas")]
        public EntityCollection<recetas> recetas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recetas>("TacosInventariosModel.FK_prod", "recetas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recetas>("TacosInventariosModel.FK_prod", "recetas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "FK_productos", "ventas")]
        public EntityCollection<ventas> ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ventas>("TacosInventariosModel.FK_productos", "ventas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ventas>("TacosInventariosModel.FK_productos", "ventas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="recetas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class recetas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto recetas.
        /// </summary>
        /// <param name="id_producto">Valor inicial de la propiedad id_producto.</param>
        /// <param name="id_insumo">Valor inicial de la propiedad id_insumo.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        public static recetas Createrecetas(global::System.String id_producto, global::System.String id_insumo, global::System.Decimal cantidad)
        {
            recetas recetas = new recetas();
            recetas.id_producto = id_producto;
            recetas.id_insumo = id_insumo;
            recetas.cantidad = cantidad;
            return recetas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                if (_id_producto != value)
                {
                    Onid_productoChanging(value);
                    ReportPropertyChanging("id_producto");
                    _id_producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_producto");
                    Onid_productoChanged();
                }
            }
        }
        private global::System.String _id_producto;
        partial void Onid_productoChanging(global::System.String value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_insumo
        {
            get
            {
                return _id_insumo;
            }
            set
            {
                if (_id_insumo != value)
                {
                    Onid_insumoChanging(value);
                    ReportPropertyChanging("id_insumo");
                    _id_insumo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_insumo");
                    Onid_insumoChanged();
                }
            }
        }
        private global::System.String _id_insumo;
        partial void Onid_insumoChanging(global::System.String value);
        partial void Onid_insumoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "FK_insum", "insumos")]
        public insumos insumos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<insumos>("TacosInventariosModel.FK_insum", "insumos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<insumos>("TacosInventariosModel.FK_insum", "insumos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<insumos> insumosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<insumos>("TacosInventariosModel.FK_insum", "insumos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<insumos>("TacosInventariosModel.FK_insum", "insumos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "FK_prod", "productos")]
        public productos productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("TacosInventariosModel.FK_prod", "productos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("TacosInventariosModel.FK_prod", "productos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<productos> productosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("TacosInventariosModel.FK_prod", "productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<productos>("TacosInventariosModel.FK_prod", "productos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TacosInventariosModel", Name="ventas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ventas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ventas.
        /// </summary>
        /// <param name="id_producto">Valor inicial de la propiedad id_producto.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        public static ventas Createventas(global::System.String id_producto, global::System.Int32 cantidad, global::System.DateTime fecha)
        {
            ventas ventas = new ventas();
            ventas.id_producto = id_producto;
            ventas.cantidad = cantidad;
            ventas.fecha = fecha;
            return ventas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                if (_id_producto != value)
                {
                    Onid_productoChanging(value);
                    ReportPropertyChanging("id_producto");
                    _id_producto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_producto");
                    Onid_productoChanged();
                }
            }
        }
        private global::System.String _id_producto;
        partial void Onid_productoChanging(global::System.String value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Int32 _cantidad;
        partial void OncantidadChanging(global::System.Int32 value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                if (_fecha != value)
                {
                    OnfechaChanging(value);
                    ReportPropertyChanging("fecha");
                    _fecha = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fecha");
                    OnfechaChanged();
                }
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TacosInventariosModel", "FK_productos", "productos")]
        public productos productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("TacosInventariosModel.FK_productos", "productos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("TacosInventariosModel.FK_productos", "productos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<productos> productosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productos>("TacosInventariosModel.FK_productos", "productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<productos>("TacosInventariosModel.FK_productos", "productos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
